# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 905b67448fcc67de54f5693bda1145907982b7976ef718a11753aef902f3350e05a5dc2634cf9eb748f8e8269d750b40e8a9bbc12c87083cc63db9be0607d980

test:
  secret_key_base: b05334a573d77bab8899cb055cc65927fb1ffb3972ecfa5d61850f32d04ca0798d406a65f96a879226aa55e43d0e50649502e5a45e60735a39acc989addabbc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
